using HarmonyLib;
using FractalSpace;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace FS_LevelEditor
{
    public static class LE_CustomErrorPopups
    {
        static readonly string ASSEMBLY_NAME = Assembly.GetExecutingAssembly().GetName().Name;

        const string ERROR_TITLE = "LEVEL EDITOR ERROR";
        const string ERROR_WARNING_PREFIX = "[ffff00]WARNING: THIS ERROR WAS GENERATED BY THE [b]LEVEL EDITOR MOD[/b]. DO NOT REPORT IT TO HAZE GAMES![-]";
        const string ERROR_PREFIX = "Please, make sure to report it to [00ffff]@Javialon_qv[-] in the official Haze Games Discord Server.";

        public static void Init()
        {
            Application.logMessageReceived += OnLogReceived;
        }

        public static void OnLogReceived(string condition, string stackTrace, LogType type)
        {
            if ((type == LogType.Error || type == LogType.Exception)    // Make sure it's an error.
                && stackTrace.Contains(ASSEMBLY_NAME))                  // Make sure is from LE and not other mod or main game log.
            {
                Show(condition, stackTrace);
            }
        }
        static void OnMelonError(string section, string text)
        {
            if (section == ASSEMBLY_NAME || text.Contains(ASSEMBLY_NAME))
            {
                if (text.Contains('\n'))
                {
                    string condition = text.Substring(0, text.IndexOf('\n'));
                    string stackTrace = text.Substring(text.IndexOf('\n') + 1);
                    Show(condition, stackTrace);
                }
                else
                {
                    Show(text, "");
                }
            }
        }

        public static void Show(string exception, string stackTrace)
        {
            var menu = MenuController.GetInstance();

            if (menu.ErrorPopupIsDisplayed())
                return;

            menu.ShowCodeErrorPopup(ERROR_TITLE, ERROR_WARNING_PREFIX + '\n' + ERROR_PREFIX, exception, stackTrace);
        }
    }
}
